#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /home
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
